### ISSUE TITLE
【寻求帮助】Network adapters don't work

### ISSUE THREAD

**Issue by Anonym121** [yuantuo666/baiduwp-php#192]
I used http://wp.nanmu.cool/ to download files from baidu. Nanmu then redirected me to https://imwcr.cn/api/bdwp/ and I did the aria2 protocol (https://imwcr.cn/api/bdwp/?help#aria2-windows). After that, the computer worked correctly and I put it in hibernation. That was yesterday.

Today my computer doesnt have internet and network adapters show "Windows is still setting up the class configuration for this device. (Code 56)" error. This is associated to conflicts with VPN.

Please, I need help to repair my network connection

device:
windows 10 Pro 21H2 browser: mozilla firefox

Please ask for  more information if needed.

我使用http://wp.nanmu.cool/从百度下载文件。 Nanmu然后将我重定向到https://imwcr.cn/api/bdwp/，我做了aria2协议（https://imwcr.cn/api/bdwp/?help#aria2-windows）。 之后，计算机正常工作，我将其置于休眠状态。 那是昨天。

今天我的电脑没有互联网，网络适配器显示“Windows 仍在为此设备设置类配置。（代码 56）”错误。 这与与 VPN 的冲突有关。

请，我需要帮助来修复我的网络连接

设备：
windows 10 Pro 21H2 浏览器：mozilla firefox

如果需要，请询问更多信息。

**Comment by lc6464** [comment]
Are you using Aria2 on your local computer? Or on another device (like a cloud server)?
If you are using Aria2 on the local computer, it may be caused by the conflict between Aria2 and your other network-related software. We cannot solve this problem. You can try to [initiate an issue to Aria2](https://github.com/aria2/aria2/issues). As a temporary solution to network problems, you can reset the network in settings (this has some consequences, see tips in settings).

**Comment by lc6464** [comment]
If you have additional questions, you can reopen the issue.
