### ISSUE TITLE
【BUG 反馈】无法正常获取文件夹有关信息

### ISSUE THREAD

**Issue by Yanda2008** [yuantuo666/baiduwp-php#221]
您可以在这里输入其他有关此 Bug 的信息。
链接错误
无法正常获取文件夹有关信息。
报错 我已经尝试了重装 
系统:Debian GNU/Linux 10 x86_64(Py3.7.9)　
Nginx 1.22.0
MySQL 5.5.62 
PHP-7.2.33
我的账户都没问题 后台都可以正常识别到 curl也装了

**Comment by lc6464** [comment]
参见 #219

**Comment by yuantuo666** [comment]
[v2.2.3](https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.3) 更新至此版本及更高可解决此问题

**Comment by Acker777** [comment]
更新后仍旧无法获取

**Comment by Acker777** [comment]
点完就这样啥也没有&nbsp;


暖阳以南浅眠未安
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 晚上11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #221)





   
仍然无法获取文件夹吗
 我这边测试文件夹和文件都没有问题

**Comment by Acker777** [comment]
文件和文件夹都不行
&nbsp;


暖阳以南浅眠未安
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 晚上11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #221)





   
仍然无法获取文件夹吗
 我这边测试文件夹和文件都没有问题

**Comment by yuantuo666** [comment]
> 文件和文件夹都不行 &nbsp; 暖阳以南浅眠未安 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月13日(星期四) 晚上11:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #221) 仍然无法获取文件夹吗 我这边测试文件夹和文件都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请打开调试模式并截图发送至issue，可能是BDUSS或STOKEN失效导致的问题

**Comment by Acker777** [comment]
后台看账号显示没问题啊&nbsp;


暖阳以南浅眠未安
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月14日(星期五) 凌晨0:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #221)





  
文件和文件夹都不行 &nbsp; 暖阳以南浅眠未安 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年10月13日(星期四) 晚上11:58 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #221) 仍然无法获取文件夹吗 我这边测试文件夹和文件都没有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
请打开调试模式并截图发送至issue，可能是BDUSS或STOKEN失效导致的问题
